package cloud

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"net/http"
	"time"
)

// Tenant merepresentasikan satu customer SaaS beserta plan tier-nya.
// Disimpan di tabel tenants dan dipakai oleh TenantAuthenticator untuk
// memvalidasi setiap request WebSocket dan REST API.
type Tenant struct {
	ID        string    `json:"id"`         // UUID — generated by PostgreSQL.
	Name      string    `json:"name"`       // Nama project / organisasi.
	Plan      string    `json:"plan"`       // free, pro, atau enterprise.
	APIKey    string    `json:"api_key"`    // pk_... — dipakai sebagai kredensial publish.
	CreatedAt time.Time `json:"created_at"` // Waktu registrasi tenant.
}

// TenantAuthenticator mengimplementasikan extensions.Authenticator dari core.
//
// Cara kerja:
//   1. Baca header X-Tenant-Key (api key tenant) dan X-User-ID (identitas user)
//   2. Validasi api key ke tabel tenants di PostgreSQL
//   3. Kembalikan userID dan tenantID jika valid
//
// Dipakai oleh handler WebSocket dan auth endpoint untuk memvalidasi
// setiap request tanpa menyentuh code core Gateway Realtime.
type TenantAuthenticator struct {
	DB *sql.DB // Koneksi PostgreSQL — diinject dari cmd/server/main.go.
}

// Authenticate membaca header X-Tenant-Key dan X-User-ID, lalu memvalidasi
// api key ke database. Mengembalikan userID, tenantID, dan status ok.
// Jika salah satu header kosong atau api key tidak ditemukan, return ok=false
// yang membuat handler core fallback ke JWT validation (untuk self-hosted user).
func (a TenantAuthenticator) Authenticate(r *http.Request) (userID, tenantID string, ok bool) {
	tenantKey := r.Header.Get("X-Tenant-Key")
	userID = r.Header.Get("X-User-ID")
	if tenantKey == "" || userID == "" {
		// Header kosong berarti ini self-hosted user — fallback ke JWT.
		return "", "", false
	}
	var t Tenant
	// Query plan tenant untuk validasi API key; field lain tidak dibaca
	// karena hanya perlu ID tenant untuk rate limiting dan usage tracking.
	err := a.DB.QueryRowContext(r.Context(),
		"SELECT id, name, plan FROM tenants WHERE api_key = $1",
		tenantKey,
	).Scan(&t.ID, &t.Name, &t.Plan)
	if err != nil {
		return "", "", false
	}
	return userID, t.ID, true
}

// GetTenantByKey mengambil tenant berdasarkan API key.
// Dipakai oleh rate limiter dan API endpoint untuk lookup tenant.
func GetTenantByKey(db *sql.DB, apiKey string) (*Tenant, error) {
	var t Tenant
	err := db.QueryRowContext(context.Background(),
		"SELECT id, name, plan, api_key, created_at FROM tenants WHERE api_key = $1",
		apiKey,
	).Scan(&t.ID, &t.Name, &t.Plan, &t.APIKey, &t.CreatedAt)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// CreateTenant mendaftarkan tenant baru dengan API key unik.
// API key dibuat dengan prefix "pk_" (publishable key) agar mudah dibedakan
// dari secret key dan credential lainnya.
//
// Tenant baru selalu dibuat dengan plan "free" — upgrade dilakukan via Stripe
// webhook yang akan mengupdate kolom plan di database.
func CreateTenant(db *sql.DB, name string) (*Tenant, error) {
	apiKey := "pk_" + genToken(16) // 16 byte random = 32 hex chars
	var t Tenant
	err := db.QueryRow(
		"INSERT INTO tenants (name, plan, api_key) VALUES ($1, $2, $3) RETURNING id, name, plan, api_key, created_at",
		name, "free", apiKey,
	).Scan(&t.ID, &t.Name, &t.Plan, &t.APIKey, &t.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create tenant: %w", err)
	}
	return &t, nil
}

// genToken menghasilkan token random hex sepanjang n byte.
// Dipakai untuk membuat API key tenant — bukan untuk kriptografi.
func genToken(n int) string {
	b := make([]byte, n)
	// rand.Read tidak pernah error pada Go ≥ 1.22.
	rand.Read(b)
	return hex.EncodeToString(b)
}

// PlanLimits mengembalikan batasan rate limit dan koneksi per tier.
// Dipakai oleh PlanRateLimiter untuk menentukan apakah request diterima atau ditolak.
//
// Tier:
//   - free:       100 events/menit,  5 koneksi (coba-coba / proyek kecil)
//   - pro:      10,000 events/menit,  1,000 koneksi (produksi menengah)
//   - enterprise: 100,000 events/menit, 10,000 koneksi (skala besar)
func PlanLimits(plan string) (eventsPerMinute int, connections int) {
	switch plan {
	case "enterprise":
		return 100_000, 10_000
	case "pro":
		return 10_000, 1_000
	default: // free
		return 100, 5
	}
}
